apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-sam-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/env-registry: "178918557969.dkr.ecr.ap-south-1.amazonaws.com"
    argocd.argoproj.io/env-image: "178918557969.dkr.ecr.ap-south-1.amazonaws.com/isl-resource-definition-framework:latest"
spec:
  project: default
  source:
    repoURL: 'https://github.com/vpawar251/test-argocd.git' # Replace with your Git repository URL
    targetRevision: main # Replace with your branch name
    path: . # Path to the directory containing this manifest
    plugin:
      name: aws-cdk-plugin # Explicitly specify the plugin name
      env: # Add environment variables for the plugin
      - name: ARGOCD_ENV_REGISTRY
        value: "178918557969.dkr.ecr.ap-south-1.amazonaws.com"
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: accessKeyId
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: secretAccessKey
      - name: AWS_DEFAULT_REGION
        value: "ap-south-1"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
